#1 Add perlin noise to height generation
QuasiStellar/Edgecase pull request #4
Opened 2022-02-28 00:27 UTC by zazamrykh

2022-02-28 17:59 UTC, QuasiStellar requested changes

2022-02-28 22:12 UTC, zazamrykh commented on Assets/Scripts/Hex.cs
> +	public static int CoordinateShift = Random.Range(10000,100000);
If CoordinateShift will set at MapGenerator we cannot to access variable without passing through metod Hex. Before you said that this is not good idea to pass variable through Hex. Also you said making global variable is not good idea too. So what we can do to solve it?

2022-02-28 22:16 UTC, zazamrykh commented on Assets/Scripts/Hex.cs
> +        int height = (int) (Mathf.PerlinNoise((float)(aPos/10.1) + CoordinateShift, (float)(bPos/10.1) + CoordinateShift) * HeightVariation);
I think SmoothnessLevel is good name of this variable. But my question how we can set SmoothnessLevel and CoordinateShift at MapGenerator is remaining open.

2022-02-28 22:17 UTC, zazamrykh commented on Assets/Scripts/MapGenerator.cs
> +    private const int MapSize = 20;
Should I change back to MapSize = 10? This is default value for this variable?

2022-03-01 06:20 UTC, QuasiStellar commented on Assets/Scripts/Hex.cs
> +	public static int CoordinateShift = Random.Range(10000,100000);
It's already "global" (public) and since it is also static, you can access it from MapGenerator like so: `Hex.Coordinate Shift`

2022-03-01 06:21 UTC, QuasiStellar commented on Assets/Scripts/Hex.cs
> +        int height = (int) (Mathf.PerlinNoise((float)(aPos/10.1) + CoordinateShift, (float)(bPos/10.1) + CoordinateShift) * HeightVariation);
Just `Smoothness` is fine.

2022-03-01 06:23 UTC, QuasiStellar commented on Assets/Scripts/MapGenerator.cs
> +    private const int MapSize = 20;
Yeah, you can check what it was before in the diff, it's colored red.

2022-03-02 22:19 UTC, QuasiStellar requested changes
Check the comments

2022-03-02 23:09 UTC, merged